import React, { useEffect, useMemo, useState } from "react";
import { listSalaryBillCodes } from "../utils/salaryBillCodeApi";
import { listInstitutes } from "../utils/instituteApi";
import { getFinalSalaryBill, listFinalBillInstitutes } from "../utils/finalSalaryBillApi";
import "./finalSalaryBill.css";
import useReportPrintPage, { printReport } from "../utils/useReportPrintPage";

/*
 * Canonical "main salary bill" rule — mirrors backend isMainSalaryBill()
 * (routes/salaryBillCodes.js), kept inline because the bundles cannot share
 * code. Main bill = Salary category, Regular (non-Difference) type, BillCode
 * without the "-BM-XXX" Bill-Month variant suffix.
 */
function isMainSalaryBill(row) {
  const code = String(row?.billCode ?? "");
  const category = String(row?.billCategory ?? "").trim().toUpperCase();
  const type = String(row?.billType ?? "").trim().toUpperCase();
  if (!code || /-BM-[A-Z]{3}$/i.test(code)) return false;
  if (category !== "SALARY") return false;
  if (type.includes("DIFFERENCE")) return false;
  if (row?.isArchived) return false;
  return true;
}

/* Closed main salary bills only — COMPLETED or LOCKED, latest month first. */
function isClosedMainSalaryBill(row) {
  if (!isMainSalaryBill(row)) return false;
  const status = String(row?.status ?? "").trim().toUpperCase();
  return status === "COMPLETED" || status === "LOCKED";
}

function compareSalaryMonthDesc(a, b) {
  const yearDiff =
    Number(b?.salaryYear || 0) - Number(a?.salaryYear || 0);
  if (yearDiff !== 0) return yearDiff;
  return Number(b?.salaryMonthNumber || 0) - Number(a?.salaryMonthNumber || 0);
}

const money = (value) =>
  Number(value || 0).toLocaleString("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });

function xmlEscape(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function cell(value, type = "String") {
  if (type === "Number") {
    const n = Number(value);
    return `<Cell><Data ss:Type="Number">${Number.isFinite(n) ? n : 0}</Data></Cell>`;
  }
  return `<Cell><Data ss:Type="String">${xmlEscape(value)}</Data></Cell>`;
}

function buildExcelWorkbook(billData, generatedBy) {
  const { bill, institute, employees, totals, counts, summary } = billData;
  const headerInfo = [
    ["FINAL SALARY BILL"],
    ["Institute", `${institute.instituteCode} — ${institute.instituteName}`],
    ["Bill Code", bill.billCode],
    ["Salary Month", bill.salaryMonthLabel || bill.salaryMonth],
    ["Salary Year", bill.salaryYear],
    ["Status", bill.status],
    ["Generated By", generatedBy],
    [],
  ];

  const columns = [
    "Sr No",
    "Employee Code",
    "Employee Name",
    "Designation",
    "Employee Type",
    "Basic Pay",
    "DA",
    "HRA",
    "MA",
    "TA",
    "Special Allowance",
    "Washing Allowance",
    "Other Earnings",
    "Gross Salary",
    "GPF",
    "GPF Advance",
    "NPS",
    "Income Tax",
    "Professional Tax",
    "Other Deduction",
    "Total Deduction",
    "Net Salary",
  ];

  const billRows = [
    ...headerInfo.map((row) =>
      `<Row>${row.map((c) => cell(c)).join("")}</Row>`
    ),
    `<Row>${columns.map((c) => cell(c)).join("")}</Row>`,
    ...employees.map(
      (row, index) =>
        `<Row>${[
          cell(index + 1, "Number"),
          cell(row.employeeCode),
          cell(row.employeeName),
          cell(row.designation),
          cell(row.employeeType),
          cell(row.basicPay, "Number"),
          cell(row.da, "Number"),
          cell(row.hra, "Number"),
          cell(row.ma, "Number"),
          cell(row.ta, "Number"),
          cell(row.specialAllowance, "Number"),
          cell(row.washingAllowance, "Number"),
          cell(row.otherEarnings, "Number"),
          cell(row.grossSalary, "Number"),
          cell(row.gpfSubscription, "Number"),
          cell(row.gpfAdvance, "Number"),
          cell(row.nps, "Number"),
          cell(row.incomeTax, "Number"),
          cell(row.professionalTax, "Number"),
          cell(row.otherDeduction, "Number"),
          cell(row.totalDeduction, "Number"),
          cell(row.netSalary, "Number"),
        ].join("")}</Row>`
    ),
    `<Row>${[
      cell("TOTAL"),
      cell(""),
      cell(""),
      cell(""),
      cell(""),
      cell(totals.basicPay, "Number"),
      cell(totals.da, "Number"),
      cell(totals.hra, "Number"),
      cell(totals.ma, "Number"),
      cell(totals.ta, "Number"),
      cell(totals.specialAllowance, "Number"),
      cell(totals.washingAllowance, "Number"),
      cell(totals.otherEarnings, "Number"),
      cell(totals.grossSalary, "Number"),
      cell(totals.gpfSubscription, "Number"),
      cell(totals.gpfAdvance, "Number"),
      cell(totals.nps, "Number"),
      cell(totals.incomeTax, "Number"),
      cell(totals.professionalTax, "Number"),
      cell(totals.otherDeduction, "Number"),
      cell(totals.totalDeduction, "Number"),
      cell(totals.netSalary, "Number"),
    ].join("")}</Row>`,
  ];

  const summaryRows = [
    `<Row>${cell("SALARY SUMMARY")}</Row>`,
    `<Row>${cell("Bill Code")}${cell(bill.billCode)}</Row>`,
    `<Row>${cell("Institute")}${cell(
      `${institute.instituteCode} — ${institute.instituteName}`
    )}</Row>`,
    `<Row>${cell("Total Employees")}${cell(counts.totalEmployees, "Number")}</Row>`,
    `<Row>${cell("Regular Employees")}${cell(
      counts.regularEmployees,
      "Number"
    )}</Row>`,
    `<Row>${cell("Fixed Employees")}${cell(counts.fixedEmployees, "Number")}</Row>`,
    `<Row>${cell("Total Gross Salary")}${cell(totals.grossSalary, "Number")}</Row>`,
    `<Row>${cell("Total Deduction")}${cell(totals.totalDeduction, "Number")}</Row>`,
    `<Row>${cell("Total Net Salary")}${cell(totals.netSalary, "Number")}</Row>`,
    `<Row>${cell("Amount in Words")}${cell(summary.amountInWords)}</Row>`,
  ];

  return `<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
 <Worksheet ss:Name="Salary Bill">
  <Table>
   ${billRows.join("\n")}
  </Table>
 </Worksheet>
 <Worksheet ss:Name="Salary Summary">
  <Table>
   ${summaryRows.join("\n")}
  </Table>
 </Worksheet>
</Workbook>`;
}

function downloadBlob(filename, content, mime) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

export default function FinalSalaryBill({ user, onBack }) {
  /* A4 PORTRAIT for this report only — utils/reportPdfConfig.js */
  useReportPrintPage("finalSalaryBill");
  const [billCodes, setBillCodes] = useState([]);
  const [institutes, setInstitutes] = useState([]);
  const [billCode, setBillCode] = useState("");
  const [instituteCode, setInstituteCode] = useState("");
  const [loadingMeta, setLoadingMeta] = useState(true);
  const [loadingBill, setLoadingBill] = useState(false);
  const [error, setError] = useState("");
  const [billData, setBillData] = useState(null);
  const [showPreview, setShowPreview] = useState(false);

  const generatedBy =
    user?.fullName || user?.name || user?.userName || user?.username || "SYSTEM";

  useEffect(() => {
    let active = true;
    setLoadingMeta(true);
    Promise.all([listSalaryBillCodes(), listInstitutes()])
      .then(([bills, inst]) => {
        if (!active) return;
        const billList = Array.isArray(bills) ? bills : [];
        /*
           Final Salary Bill shows ONLY closed main salary months:
           COMPLETED/LOCKED main Salary bills (no OPEN, no BM variants,
           no DA Difference, no archived). Salary Month controls the list.
        */
        const eligible = billList
          .filter(isClosedMainSalaryBill)
          .sort(compareSalaryMonthDesc);
        const instList = (Array.isArray(inst) ? inst : []).map((row) => ({
          id: row.instituteId ?? row.id,
          code: row.instituteCode || row.code || "",
          name: row.instituteName || row.name || "",
        }));
        setBillCodes(eligible);
        setInstitutes(instList);
        if (eligible.length) {
          setBillCode(eligible[0].billCode || "");
        } else {
          setError("No completed/locked salary months available.");
        }
        if (instList.length) setInstituteCode(instList[0].code);
      })
      .catch(() => {
        if (active) setError("Unable to load bill codes or institutes.");
      })
      .finally(() => {
        if (active) setLoadingMeta(false);
      });
    return () => {
      active = false;
    };
  }, []);

  /*
     Institutes applicable to the selected locked salary month. Falls back
     to the full master list if the month lookup fails, so selection can
     never strand the user with an empty dropdown.
  */
  useEffect(() => {
    if (!selectedBillMeta) return;
    let active = true;
    listFinalBillInstitutes({
      salaryYear: selectedBillMeta.salaryYear,
      salaryMonthNumber: selectedBillMeta.salaryMonthNumber,
    })
      .then((rows) => {
        if (!active) return;
        const list = (Array.isArray(rows) ? rows : [])
          .map((row) => ({
            id: row.instituteId ?? row.id,
            code: row.instituteCode || row.code || "",
            name: row.instituteName || row.name || "",
          }))
          .filter((row) => row.code);
        if (list.length) {
          setInstitutes(list);
          setInstituteCode((prev) =>
            list.some((row) => row.code === prev) ? prev : list[0].code
          );
        }
      })
      .catch(() => {
        /* Keep the master list fallback already loaded above. */
      });
    return () => {
      active = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [billCode]);

  const selectedInstitute = useMemo(
    () => institutes.find((row) => row.code === instituteCode) || null,
    [institutes, instituteCode]
  );

  const selectedBillMeta = useMemo(
    () => billCodes.find((row) => row.billCode === billCode) || null,
    [billCodes, billCode]
  );

  const handleViewBill = async () => {
    setError("");
    setShowPreview(false);
    if (!billCode) {
      setError("Please select Salary Bill Code.");
      return;
    }
    if (!instituteCode) {
      setError("Please select Institute.");
      return;
    }

    try {
      setLoadingBill(true);
      const result = await getFinalSalaryBill(
        {
          billCode,
          instituteCode,
          instituteId: selectedInstitute?.id,
        },
        user
      );
      setBillData(result);
      if (!result.hasData) {
        setError(
          result.message ||
            "No salary data found for the selected Bill Code and Institute."
        );
      }
    } catch (err) {
      setBillData(null);
      setError(err.message || "Unable to load final salary bill.");
    } finally {
      setLoadingBill(false);
    }
  };

  const canOfficialActions =
    billData?.officialFinal && billData?.hasData && !billData?.warning;

  const handlePrint = () => {
    if (!canOfficialActions) {
      alert(
        billData?.warning ||
          "Final bill is not available until the bill is completed."
      );
      return;
    }
    setShowPreview(true);
    setTimeout(() => printReport("finalSalaryBill"), 200);
  };

  const handleExportPdf = () => {
    if (!canOfficialActions) {
      alert(
        billData?.warning ||
          "Final bill is not available until the bill is completed."
      );
      return;
    }
    setShowPreview(true);
    setTimeout(() => {
      printReport("finalSalaryBill");
    }, 250);
  };

  const handleExportExcel = () => {
    if (!canOfficialActions) {
      alert(
        billData?.warning ||
          "Final bill is not available until the bill is completed."
      );
      return;
    }
    const xml = buildExcelWorkbook(billData, generatedBy);
    downloadBlob(
      `Final-Salary-Bill-${billData.bill.billCode}-${billData.institute.instituteCode}.xls`,
      xml,
      "application/vnd.ms-excel"
    );
  };

  return (
    <div className="fsb-page">
      <div className="fsb-back no-print">
        <button type="button" className="fsb-link" onClick={onBack}>
          ← Back
        </button>
      </div>

      <div className="fsb-title-row no-print">
        <div>
          <h1>FINAL SALARY BILL</h1>
          <p>View, print and export completed / locked salary bills (read-only)</p>
        </div>
      </div>

      <section className="fsb-card no-print">
        <div className="fsb-filters">
          <label>
            <span>Salary Bill Code</span>
            <select
              value={billCode}
              disabled={loadingMeta}
              onChange={(e) => {
                setBillCode(e.target.value);
                setBillData(null);
                setError("");
              }}
            >
              <option value="">Select Bill Code</option>
              {billCodes.map((row) => (
                <option key={row.billCode} value={row.billCode}>
                  {row.billCode} ({String(row.status || "").toUpperCase()})
                </option>
              ))}
            </select>
          </label>

          <label>
            <span>Institute</span>
            <select
              value={instituteCode}
              disabled={loadingMeta || institutes.length === 0}
              onChange={(e) => {
                setInstituteCode(e.target.value);
                setBillData(null);
                setError("");
              }}
            >
              <option value="">Select Institute</option>
              {institutes.map((row) => (
                <option key={row.code} value={row.code}>
                  {row.code} — {row.name}
                </option>
              ))}
            </select>
          </label>

          <div className="fsb-filter-action">
            <button
              type="button"
              className="fsb-btn fsb-btn-primary"
              disabled={loadingBill || loadingMeta}
              onClick={handleViewBill}
            >
              {loadingBill ? "Loading..." : "VIEW BILL"}
            </button>
          </div>
        </div>

        {selectedBillMeta ? (
          <div className="fsb-status-line">
            <span>
              Bill Code: <strong>{selectedBillMeta.billCode}</strong>
            </span>
            <span>
              Salary Month:{" "}
              <strong>
                {selectedBillMeta.billCode || selectedBillMeta.salaryMonth}
              </strong>
            </span>
            <span>
              Status:{" "}
              <strong className={`fsb-badge status-${String(selectedBillMeta.status || "").toLowerCase()}`}>
                {String(selectedBillMeta.status || "").toUpperCase()}
              </strong>
            </span>
          </div>
        ) : null}

        {error ? <div className="fsb-error">{error}</div> : null}
        {billData?.warning ? (
          <div className="fsb-warning" role="alert">
            {billData.warning}
            <div className="fsb-warning-sub">
              Bill is OPEN. Final bill is not available until the bill is
              completed.
            </div>
          </div>
        ) : null}
      </section>

      {billData?.hasData ? (
        <section className="fsb-card no-print">
          <div className="fsb-actions">
            <button
              type="button"
              className="fsb-btn"
              disabled={!canOfficialActions}
              onClick={() => setShowPreview(true)}
            >
              Print Preview
            </button>
            <button
              type="button"
              className="fsb-btn"
              disabled={!canOfficialActions}
              onClick={handlePrint}
            >
              Print
            </button>
            <button
              type="button"
              className="fsb-btn"
              disabled={!canOfficialActions}
              onClick={handleExportPdf}
            >
              Export PDF
            </button>
            <button
              type="button"
              className="fsb-btn"
              disabled={!canOfficialActions}
              onClick={handleExportExcel}
            >
              Export Excel
            </button>
            <button
              type="button"
              className="fsb-btn"
              onClick={() => {
                setShowPreview(false);
                setBillData(null);
              }}
            >
              Close
            </button>
          </div>
          {!canOfficialActions ? (
            <p className="fsb-hint">
              Official print/export is enabled only for COMPLETED or LOCKED
              bills.
            </p>
          ) : null}
        </section>
      ) : null}

      {billData?.hasData ? (
        <div
          className={`fsb-bill-surface ${showPreview ? "preview-open" : ""}`}
          id="final-salary-bill-print"
        >
          <div className="fsb-print-toolbar no-print">
            <strong>Print Preview</strong>
            <div>
              <button type="button" className="fsb-btn" onClick={handlePrint}>
                Print
              </button>
              <button
                type="button"
                className="fsb-btn"
                onClick={handleExportPdf}
              >
                Export PDF
              </button>
              <button
                type="button"
                className="fsb-btn"
                onClick={handleExportExcel}
              >
                Export Excel
              </button>
              <button
                type="button"
                className="fsb-btn"
                onClick={() => setShowPreview(false)}
              >
                Close
              </button>
            </div>
          </div>

          <header className="fsb-bill-header">
            <div className="fsb-dept">
              Government / Department — DP Cell Salary
            </div>
            <h2>FINAL SALARY BILL</h2>
            <div className="fsb-header-grid">
              <div>
                <span>Institute Name</span>
                <strong>{billData.institute.instituteName}</strong>
              </div>
              <div>
                <span>Institute Code</span>
                <strong>{billData.institute.instituteCode}</strong>
              </div>
              <div>
                <span>Salary Bill Code</span>
                <strong>{billData.bill.billCode}</strong>
              </div>
              <div>
                <span>Salary Month</span>
                <strong>
                  {billData.bill.salaryMonthLabel || billData.bill.salaryMonth}
                </strong>
              </div>
              <div>
                <span>Salary Year</span>
                <strong>{billData.bill.salaryYear}</strong>
              </div>
              <div>
                <span>Bill Status</span>
                <strong>{String(billData.bill.status || "").toUpperCase()}</strong>
              </div>
              <div>
                <span>Generated Date</span>
                <strong>
                  {billData.generatedDate
                    ? new Date(billData.generatedDate).toLocaleString("en-IN")
                    : "-"}
                </strong>
              </div>
              <div>
                <span>Generated By</span>
                <strong>{generatedBy}</strong>
              </div>
            </div>
          </header>

          <section className="fsb-summary-box">
            <h3>SALARY SUMMARY</h3>
            <div className="fsb-summary-grid">
              <div>
                <span>Total Employees</span>
                <strong>{billData.counts.totalEmployees}</strong>
              </div>
              <div>
                <span>Regular</span>
                <strong>{billData.counts.regularEmployees}</strong>
              </div>
              <div>
                <span>Fixed</span>
                <strong>{billData.counts.fixedEmployees}</strong>
              </div>
              <div>
                <span>Total Gross Salary</span>
                <strong>₹ {money(billData.summary.totalGrossSalary)}</strong>
              </div>
              <div>
                <span>Total Deduction</span>
                <strong>₹ {money(billData.summary.totalDeduction)}</strong>
              </div>
              <div>
                <span>Total Net Salary</span>
                <strong>₹ {money(billData.summary.totalNetSalary)}</strong>
              </div>
            </div>
            <div className="fsb-words">
              <span>Amount in Words</span>
              <strong>{billData.summary.amountInWords}</strong>
            </div>
          </section>

          <div className="fsb-table-wrap">
            <table className="fsb-table">
              <thead>
                <tr>
                  <th>Sr</th>
                  <th>Emp Code</th>
                  <th>Employee Name</th>
                  <th>Designation</th>
                  <th>Type</th>
                  <th className="num">Basic</th>
                  <th className="num">DA</th>
                  <th className="num">HRA</th>
                  <th className="num">MA</th>
                  <th className="num">TA</th>
                  <th className="num">Special</th>
                  <th className="num">Washing</th>
                  <th className="num">Other Earn.</th>
                  <th className="num">Gross</th>
                  <th className="num">GPF</th>
                  <th className="num">GPF Adv</th>
                  <th className="num">NPS</th>
                  <th className="num">IT</th>
                  <th className="num">PT</th>
                  <th className="num">Other Ded</th>
                  <th className="num">Tot Ded</th>
                  <th className="num">Net</th>
                </tr>
              </thead>
              <tbody>
                {billData.employees.map((row, index) => (
                  <tr key={`${row.billCodeId ?? row.billCode ?? "bill"}-${row.employeeId || index}`}>
                    <td>{index + 1}</td>
                    <td>{row.employeeCode}</td>
                    <td>{row.employeeName}</td>
                    <td>{row.designation}</td>
                    <td>{row.employeeType}</td>
                    <td className="num">{money(row.basicPay)}</td>
                    <td className="num">{money(row.da)}</td>
                    <td className="num">{money(row.hra)}</td>
                    <td className="num">{money(row.ma)}</td>
                    <td className="num">{money(row.ta)}</td>
                    <td className="num">{money(row.specialAllowance)}</td>
                    <td className="num">{money(row.washingAllowance)}</td>
                    <td className="num">{money(row.otherEarnings)}</td>
                    <td className="num">{money(row.grossSalary)}</td>
                    <td className="num">{money(row.gpfSubscription)}</td>
                    <td className="num">{money(row.gpfAdvance)}</td>
                    <td className="num">{money(row.nps)}</td>
                    <td className="num">{money(row.incomeTax)}</td>
                    <td className="num">{money(row.professionalTax)}</td>
                    <td className="num">{money(row.otherDeduction)}</td>
                    <td className="num">{money(row.totalDeduction)}</td>
                    <td className="num">{money(row.netSalary)}</td>
                  </tr>
                ))}
              </tbody>
              <tfoot>
                <tr className="fsb-total-row">
                  <td colSpan={5}>TOTAL</td>
                  <td className="num">{money(billData.totals.basicPay)}</td>
                  <td className="num">{money(billData.totals.da)}</td>
                  <td className="num">{money(billData.totals.hra)}</td>
                  <td className="num">{money(billData.totals.ma)}</td>
                  <td className="num">{money(billData.totals.ta)}</td>
                  <td className="num">
                    {money(billData.totals.specialAllowance)}
                  </td>
                  <td className="num">
                    {money(billData.totals.washingAllowance)}
                  </td>
                  <td className="num">{money(billData.totals.otherEarnings)}</td>
                  <td className="num">{money(billData.totals.grossSalary)}</td>
                  <td className="num">
                    {money(billData.totals.gpfSubscription)}
                  </td>
                  <td className="num">{money(billData.totals.gpfAdvance)}</td>
                  <td className="num">{money(billData.totals.nps)}</td>
                  <td className="num">{money(billData.totals.incomeTax)}</td>
                  <td className="num">
                    {money(billData.totals.professionalTax)}
                  </td>
                  <td className="num">{money(billData.totals.otherDeduction)}</td>
                  <td className="num">{money(billData.totals.totalDeduction)}</td>
                  <td className="num">{money(billData.totals.netSalary)}</td>
                </tr>
              </tfoot>
            </table>
          </div>

          <section className="fsb-certification">
            <h3>Certification / Signatures</h3>
            <div className="fsb-sign-grid">
              <div>
                <span>Prepared By</span>
                <div className="fsb-sign-line" />
              </div>
              <div>
                <span>Checked By</span>
                <div className="fsb-sign-line" />
              </div>
              <div>
                <span>Accountant / Clerk</span>
                <div className="fsb-sign-line" />
              </div>
              <div>
                <span>Head of Office / Principal</span>
                <div className="fsb-sign-line" />
              </div>
              <div>
                <span>Auditor</span>
                <div className="fsb-sign-line" />
              </div>
              <div>
                <span>Authorized Signature</span>
                <div className="fsb-sign-line" />
              </div>
            </div>
          </section>

          <footer className="fsb-bill-footer">
            <span>
              Generated Date:{" "}
              {billData.generatedDate
                ? new Date(billData.generatedDate).toLocaleString("en-IN")
                : "-"}
            </span>
            <span>Generated By: {generatedBy}</span>
            <span className="fsb-page-indicator">
              {billData.institute.instituteName} | {billData.bill.billCode} |{" "}
              {billData.bill.salaryMonthLabel || billData.bill.salaryMonth}
            </span>
          </footer>
        </div>
      ) : null}
    </div>
  );
}
